### ISSUE TITLE
Cognito error

### ISSUE THREAD

**Issue by devergranne** [awslabs/serverless-automated-ui-testing#2]
Hello, 

I'm following the tutorial and i'm getting this when deploying :

1 validation error detected: Value 'StatusPageCognitoIP_automated-ui-testing2' at 'identityPoolName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w ]+ (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ValidationException; Request ID: 64df645c-628e-11e8-aef3-11b46e49f99d)

Now it's working when you remove the setup for the name : 

```
      IdentityPoolName:
        Fn::Sub: StatusPageCognitoIP_${AWS::StackName}
```

**Comment by beatleboy501** [comment]
If your `identityPoolName` doesn't match the regular expression "[\w]+" then it will fail. The best way to work around it is to name your repo and all of your parameters the exact same thing. You can test your name against the regular expression here: https://www.regextester.com/?fam=107415. Try to use all lower case with no numbers, dashes, underscores, or any other special characters.

**Comment by ghost** [comment]
In README.md the Step 3 has a typing error in it.  The "a" out of ".yaml" is missing. It should read.

aws cloudformation create-stack --stack-name automated-ui-testing --template-body file://automated-ui-testing.yaml --parameters file://automated-ui-testing-params.json --capabilities CAPABILITY_NAMED_IAM

**Comment by ghost** [comment]
In README.md Step 3, the "stack name" of "automated-ui-testing", the "-" breaks the abovementioned regular expression for IdentityPoolName.

The below is successful.

aws cloudformation create-stack --stack-name automateduitesting --template-body file://automated-ui-testing.yaml --parameters file://automated-ui-testing-params.json --capabilities CAPABILITY_NAMED_IAM

**Comment by ghost** [comment]
This issue was because the stack name used in the example contains hyphen(-) which is not accepted in Cognito Identity Pool name. I have changed it to use underscore(_) now. Also the typo in the create stack code example has been fixed.

**Comment by mrowles** [comment]
@p-palanis I wonder if there is a bug open with Cognito team, the regex they provide for the allowed pattern says hyphens are fine (and often builds are ok): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html
